---
title: "Side Event to the FAO Science and Innovation Forum"
date: December 7th, 2018
links:
  - label: IBBA
    url: "https://ibba.cnr.it/en/"
  - label: ISPAAM
    url: "https://https://www.ispaam.cnr.it/?lang=en"
  - label: Email
    url: "mailto:biffani@ibba.cnr.it"
output:
  postcards::trestles
---
 
## Animal Resources for a Sustainable Environment

### When: 

12 October 2022

### Where:

### Outline

The event will focus on recent advancements in animal breeding, management and welfare of livestock other than cattle. Special attention will be giving to species like buffaloes, sheep and goats. These species are efficient converter of poor quality forages into high quality milk and meat and are going to be determinant to economic and environmental sustainability worldwide. Genomic selection as well as application of machine learning algorithms for management purposes are effective solutions for the near future.

The idea is not only to present scientific contributions and on-going projects but also to listen to who, like breeders’ associations, are trying to turn ideas into practice.    

### LIST OF THE PRESENTATIONS:

#### Scientific Side

* Tania Bobbo, IBBA-CNR, Milan, Italy
* Paul Boettcher, AGA-FAO, Rome, Italy
* Bianca Castiglioni, IBBA-CNR, Milan, Italy
* Alessandra Iannuzzi, ISPAAM-CNR, Naples, Italy

#### Breeder Association Side

* Mayra Goméz, ANASB, Caserta, Italy
* Alessio Negro, AssoNaPa, Rome, Italy

